from skfuzzy import control as ctrl

def create_fuzzy_rules(frequency, available_time, excess_weight, adherence, fitness, intensity):
    rules = [
        ctrl.Rule(fitness["high"], intensity["high"]),
        ctrl.Rule(fitness["medium_high"], intensity["medium_high"]),
        ctrl.Rule(fitness["medium"], intensity["medium"]),
        ctrl.Rule(fitness["low_medium"], intensity["low_medium"]),
        ctrl.Rule(fitness["low"], intensity["low"]),
        ctrl.Rule(available_time["high"] & fitness["high"], intensity["medium_high"]),
        ctrl.Rule(available_time["high"] & fitness["medium_high"], intensity["medium"]),
        ctrl.Rule(available_time["high"] & fitness["medium"], intensity["low_medium"]),
        ctrl.Rule(frequency["low"] & fitness["high"], intensity["high"]), 
        ctrl.Rule(frequency["low"] & fitness["medium_high"], intensity["high"]), 
        ctrl.Rule(frequency["low"] & fitness["medium"], intensity["medium_high"]), 
        ctrl.Rule(frequency["low"] & fitness["low_medium"], intensity["medium"]),
        ctrl.Rule(frequency["low"] & fitness["low"], intensity["low_medium"]), 
        ctrl.Rule(available_time["low"] & fitness["high"], intensity["high"]), 
        ctrl.Rule(available_time["low"] & fitness["medium_high"], intensity["high"]), 
        ctrl.Rule(available_time["low"] & fitness["medium"], intensity["medium_high"]), 
        ctrl.Rule(available_time["low"] & fitness["low_medium"], intensity["medium"]), 
        ctrl.Rule(available_time["low"] & fitness["low"], intensity["low_medium"]), 
        ctrl.Rule(frequency["high"] & fitness["high"], intensity["medium_high"]), 
        ctrl.Rule(frequency["high"] & fitness["medium_high"], intensity["medium"]), 
        ctrl.Rule(frequency["high"] & fitness["medium"], intensity["low_medium"]), 
        ctrl.Rule(frequency["high"] & fitness["low_medium"], intensity["low"]), 
        ctrl.Rule(adherence["high"] & fitness["high"], intensity["high"]), 
        ctrl.Rule(adherence["high"] & fitness["medium_high"], intensity["high"]), 
        ctrl.Rule(adherence["high"] & fitness["medium"], intensity["medium_high"]), 
        ctrl.Rule(adherence["high"] & fitness["low_medium"], intensity["medium"]), 
        ctrl.Rule(adherence["high"] & fitness["low"], intensity["low_medium"]), 
        ctrl.Rule(adherence["low"] & fitness["high"], intensity["medium_high"]), 
        ctrl.Rule(adherence["low"] & fitness["medium_high"], intensity["medium"]), 
        ctrl.Rule(adherence["low"] & fitness["medium"], intensity["low_medium"]), 
        ctrl.Rule(adherence["low"] & fitness["low_medium"], intensity["low"]), 
        ctrl.Rule(adherence["moderate"] & fitness["high"], intensity["high"]), 
        ctrl.Rule(adherence["moderate"] & fitness["medium_high"], intensity["medium_high"]), 
        ctrl.Rule(adherence["moderate"] & fitness["medium"], intensity["medium"]), 
        ctrl.Rule(adherence["moderate"] & fitness["low_medium"], intensity["low_medium"]), 
        ctrl.Rule(adherence["moderate"] & fitness["low"], intensity["low"]), 
        ctrl.Rule(excess_weight["moderate"] & fitness["low"], intensity["low_medium"]), 
        ctrl.Rule(excess_weight["moderate"] & fitness["low_medium"], intensity["medium"]), 
        ctrl.Rule(excess_weight["moderate"] & fitness["medium"], intensity["medium_high"]), 
        ctrl.Rule(excess_weight["moderate"] & fitness["medium_high"], intensity["high"])
    ]
    return rules
